version: "2"

run:
  timeout: 3m

linters:
  enable:
    - revive
    - misspell
    - unconvert
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
